data_ingestion:
  bucket_name: "hotel-reservation-bucket"
  bucket_file_name: "hotel_reservations.csv"
  train_ratio: 0.8

data_preprocessing:
  categorical_columns:
    -  type_of_meal_plan
    -  market_segment_type
    -  room_type_reserved
    -  required_car_parking_space
    -  repeated_guest
    -  booking_status
  numerical_columns:
    -  no_of_adults
    -  no_of_children
    -  no_of_weekend_nights
    -  no_of_week_nights
    -  lead_time
    -  arrival_year
    -  arrival_month
    -  arrival_date
    -  no_of_previous_cancellations
    -  no_of_previous_bookings_not_canceled
    -  avg_price_per_room
    -  no_of_special_requests
  skewed_threshold: 5
  no_of_features: 10